trigger:
- none

stages:
- stage:
  jobs:
  - job:
    pool:
     vmImage: ubuntu-latest
    steps:
    - task: Maven@1
      displayName: 'Maven $(mavenPOMFile)'
      inputs:
        mavenPomFile: pom.xml
        testResultsFiles: '**/TEST*.xml'

    - task: CopyFiles@2
      displayName: 'Copy File to: $(TargetFolder)'
      inputs:
        SourceFolder: '$(Build.SourcesDirectory)'
        Contents: |
         **/*.war 
         **/*jar-with-dependencies.jar
        TargetFolder: '$(Build.ArtifactStagingDirectory)'
        flattenFolders: true

    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'drop'
        publishLocation: 'Container'

- stage: "DeployToDev"
  displayName: "Deploying to Dev Env"
  jobs:
  - job:
    pool:
     vmImage: ubuntu-latest
    steps:
    - task: AzureRmWebAppDeployment@4
      inputs:
        ConnectionType: 'AzureRM'
        azureSubscription: 'Azure Pass - Sponsorship(7a64ff72-0f8c-4445-947b-2c65f88d344b)'
        appType: 'webAppLinux'
        WebAppName: 'pet-clinic-java'
        packageForLinux: '$(Pipeline.Workspace)/**/*.war'